name: pasuhisab
version: 2.0.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cross_connectivity: ^3.1.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter_easyloading: ^3.0.5
  get: 4.6.6
  hexcolor: ^3.0.1
  http: ^1.2.0
  intl: ^0.19.0
  nepali_utils: ^3.0.4
  package_info: ^2.0.2
  path_provider: ^2.1.2
  pdf: ^3.10.7
  sqflite: ^2.3.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
