import 'package:get/get_navigation/src/root/internacionalization.dart';
import 'package:pasuhisab/app/constants/Strings.dart';

class TLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          appName: appName,
          logout: logout,
          register: register,
          googleSingIn: googleSingIn,
          email: email,
          pin: pin,
          rpin: rpin,
          forgetpin: forgetpin,
          phone: phone,
       
          todayPrice: todayPrice,
          search: search,
          total: total,
          qty: qty,
          address: address,
          themeschange: themeschange,
          paymentsetting: paymentsetting,
          languageSetting: languageSetting,
          category: category,
          chick: chick,
          //From here new

          ok: ok,
          cancel: cancel,
          edit: edit,
          save: save,
          update: update,

          selectCategory: selectCategory,
          boiler: boiler,
          bhale: bhale,
          kadaknath: kadaknath,
          quail: quail,
          turkey: turkey,
          parent: parent,
          billno: billno,
          date: date,
          image: image,
          name: name,
          rate: rate,
          income: income,
          expenses: expenses,
          account: account,
          setting: setting,
          lot: lot,
          profit: profit,
          loss: loss,
          balance: balance,
          plus: plus,
          minus: minus,
          remaning: remaning,
          dead: dead,
          dana: dana,
          bora: bora,
          other: other,
          labor: labor,
          medicine: medicine,
          bhus: bhus,
          sold: sold,
          chicken: chicken,
          piece: piece,
          weight: weight,
          t: t,
          price: price,
          note: note,
          clicknote: clicknote,
          particular: particular,
          electricity: electricity,
          el: el,
          rent: rent,
          re: re,
          rs:rs,
          water: water,
          wat: wat,
          extra: extra,
          travel: travel,
          cost: cost,
          ch: ch,
          mol: mol,
          egg: egg,
          finished: finished,
          selling: selling,
          add: add,
          noInternet: noInternet,
          clear: clear,
          report: report,
          average: average,
          maxx: maxx,
          minn: minn,
          delete: delete,
          the: the,
          clickmessage: clickmessage,
          printing: printing,
          title: title,
          description: description,
          addnote: addnote,
          updatenote: updatenote,
          addfromtop: addfromtop,
          english: english,
          nepali: nepali,

          info: info,
          error: error,
          warning: warning,
          deleteMessage: deleteMessage,
          saveMessage: saveMessage,
          updateMessage: updateMessage,
          errorMessage: errorMessage,
          deleteMessageWarning:deleteMessageWarning,
          nodatafound:nodatafound,
          remark:remark,
          close:close,
          kg:kg,
          amount:amount,
          sn:sn,
          rm:rm,
          ret:ret,
          consume:consume,
          about:about,
          sharing:sharing,
        },
        'ne_NP': {
          about:'हाम्रो बारेमा',
          sharing:'सेयर',
          sn:'सि.',
          rm:'मेट्',
          ret:'फिर्ता',
          consume:'उपभोग',

          amount:'रकम',
          kg:'के.जी',
          close:'बन्द गर्नु',
          remark:'टिप्पणी',
          nodatafound:'कुनै जानकारी भेटिएन',
          deleteMessageWarning:'के तपाइँ यसलाई मेटाउन निश्चित हुनुहुन्छ?',
          info: 'जानकारी',
          error: 'त्रुटि सन्देश',
          warning: 'चेतावनी',
          deleteMessage: 'सफलतापूर्वक मेटाईयो',
          saveMessage: 'जानकारी सफलतापूर्वक बचत गरियो।',
          updateMessage: 'जानकारी सफलतापूर्वक अपडेट गरियो।',
          errorMessage: 'माफ गर्नुहोस् केहि गलत भयो।',
          title: 'शीर्षक',
          description: 'वर्णन',
          addnote: 'नोट थप्नुहोस् ',
          updatenote: 'परिमार्जन गर्नुहोस्',
          addfromtop: 'कृपया माथिबाट थप्नुहोस्।',
          printing: 'प्रिन्ट गर्नुहोस्',
          appName: 'मासु',
          register: 'दर्ता गर्नु',
          googleSingIn: 'गुगल साइन इन',
          email: 'ईमेल',
          pin: 'पासवर्ड',
          forgetpin: 'पासवोर्ड भुले ?',
          phone: 'मोबाइल नम्बर',
          rpin: 'पुनः पासवर्ड',
          rs: 'रु.',
          todayPrice: 'आजको मूल्य',
          search: 'खोजी गर्नुहोस्',
          total: 'जम्मा',
          qty: 'मात्रा',
          address: 'प्रयोगकर्ताको ठेगाना',
          paymentsetting: 'भुक्तानी विधि',
          languageSetting: 'भाषा सेटिंग',
          category: 'श्रेणी',
          chick: 'चल्ला',

          //from here
          ok: 'ठिक छ',
          cancel: 'रद्द गर्नुहोस्',
          edit: 'मिलाउनुस्',
          save: 'बचत गर्नुहोस्',
          update: 'परिवर्तन गर्नुहोस्',

          selectCategory: 'चयन गर्नुहोस्',
          boiler: 'बोइलर',
          bhale: 'भाले',
          kadaknath: 'कडकनाथ',
          quail: 'बटेर',
          turkey: 'टर्की',
          parent: 'पारेन्ट',
          billno: 'बिल न.',
          date: 'मिति',
          image: 'फोटो',
          name: 'नाम',
          rate: 'दर',
          income: 'आमदानी',
          expenses: 'खर्च',
          account: 'खाता',
          setting: 'सेटिंग',
          lot: 'लट',
          profit: 'नाफा',
          loss: 'घाटा',
          balance: 'ब्यालेन्स',
          plus: '+',
          minus: '-',
          remaning: 'बाँकी',
          dead: 'मरेको',
          dana: 'दाना',
          bora: 'बोरा',
          other: 'अन्य',
          labor: 'श्रमिक',
          medicine: 'औषधी',
          bhus: 'भुस्',
          sold: 'बेचिको',
          chicken: 'कुखुरा',
          piece: 'गोटा',
          weight: 'तौल',
          t: t,
          price: 'मूल्य',
          note: 'नोट',
          clicknote: 'विवरणहरू हेर्न  Row मा थिच्नुनुहोस्।',
          particular: 'विशेष',
          electricity: 'बिजुली',
          el: el,
          rent: 'भाडा',
          re: re,
          water: 'पानी',
          wat: wat,
          extra: 'अतिरिक्त',
          travel: 'यात्रा',
          cost: 'लागत',
          ch: ch,
          mol: 'मोल',
          egg: 'अण्डा',
          finished: 'समाप्त गर्नुहोस्',
          selling: 'बेचेको',
          add: 'थप्नुहोस्',
          noInternet: 'कृपया तपाईंको नेटवर्कमा जडान गर्नुहोस्।',
          clear: 'सफा',
          report: 'रिपोर्ट',
          average: 'औसत',
          maxx: 'अधिकतम',
          minn: 'घटिमा',
          delete: 'मेटाउनुहोस्',
          the: 'यो',
          clickmessage: 'विवरण हेर्न प्रत्येक आईटममा क्लिक गर्नुहोस्।',
          english: 'अंग्रेजी',
          nepali: 'नेपाली',
        }
      };
}
